### ISSUE TITLE
Glad you're a fan!

### ISSUE THREAD

**Issue by quanah** [qmachine/quanah#4]
Thanks?

--Quanah

**Comment by wilkinson** [comment]
Indeed hahaha :+1:

**Comment by quanah** [comment]
How did you come up with using my name, anyhow? :)

**Comment by wilkinson** [comment]
Because [Quanah Parker](https://en.wikipedia.org/wiki/Quanah_Parker) is a fascinating historical figure. Maybe I should put that in the documentation when I start fleshing that out :-)

**Comment by quanah** [comment]
Cool, yeah, I'm aware of who he is, since my parents named me after him.

There is also now a musician going by Quanah, although I don't know if that's a stage name or real name. https://quanah.bandcamp.com/
